
"""
/***************************************************************************
 xml_ua
                                 A QGIS plugin
 Processing ukrainian cadastral files.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-01
        copyright            : (C) 2024 by Mike
        email                : michael.krechkivski@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__version__ = "v0.0.7"  # Цей рядок буде замінено на тег під час збірки


def classFactory(iface):  # pylint: disable=invalid-name
    """Load xml_ua class from file xml_ua.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """

    from .xml_ua import xml_ua
    return xml_ua(iface)
