# -*- coding: utf-8 -*-
# xml_ua.py
"""
/***************************************************************************
 xml_ua
                                 A QGIS plugin
 Processing ukrainian cadastral files.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-01
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Michael.Krechkivski@gmail.com
        email                : michael.krechkivski@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
#✔️ 2025.10.02 12:24
# region Import 
import os
import os.path
import math
import shutil
import glob
import copy

from qgis.core import Qgis
from qgis.core import QgsGeometry
from qgis.core import QgsFeature
from qgis.core import QgsWkbTypes
from qgis.core import QgsMapLayer
from qgis.core import QgsProject
from qgis.core import QgsVectorLayer
from qgis.core import QgsVectorLayerEditUtils
from qgis.core import QgsLayerTreeGroup
from qgis.core import QgsRasterLayer
from qgis.core import QgsLayerTreeLayer
from qgis.gui import QgsLayerTreeViewMenuProvider
from qgis.core import QgsApplication

from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtCore import QObject
from qgis.PyQt.QtCore import QSettings
from qgis.PyQt.QtCore import QTranslator
from qgis.PyQt.QtCore import QCoreApplication

from qgis.PyQt.QtGui import QIcon

from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtWidgets import QMenu
from qgis.PyQt.QtWidgets import QToolBar
from qgis.PyQt.QtWidgets import QToolButton
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.PyQt.QtWidgets import QStyle
from qgis.PyQt.QtWidgets import QInputDialog
from qgis.PyQt.QtWidgets import QFileDialog
from lxml import etree

from qgis.core import QgsWkbTypes
# початковий варіант для отримання об'єкта QgisInterface
from qgis.utils import iface
# рекомендований Gemini варіант для отримання об'єкта QgisInterface
# from qgis.gui import QgisInterface


#from PyQt5.QtWidgets import QMessageBox

# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .dockwidget import xml_uaDockWidget
#from .layers import xmlUaLayers
from .points import Points
from .lines import PLs
from .zone import CadastralZoneInfo
from .quarters import CadastralQuarters
from .parcels import CadastralParcel
from .lands import LandsParcels
from .leases import Leases
from .subleases import Subleases
from .restrictions import Restrictions
from .adjacents import AdjacentUnits

from .common import size
from .common import logFile
from .common import log_msg
from .common import connector
from .common import xml_template
from .common import geometry_to_string
from .new_xml import NewXmlCreator

# endregion

#class xml_ua(QgsLayerTreeViewMenuProvider):
class xml_ua:
    """QGIS Plugin Implementation."""

    # after load QGIS, without project 
    def __init__(self, iface):

    #✔️ 2025.05.17 цей варіант рекомендований Gemini аналогічний початковому
    # def __init__(self, iface: QgisInterface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        #super().__init__()
        #✔️ 2025.05.17 у рекомендаціях: iface: QgisInterface
        # а було: from qgis.utils import iface
        # log_calls(logFile, f"iface = {iface}")

        self.iface = iface
        self.project = None
        self.xml_layers = None
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(self.plugin_dir,'i18n',f'xml_ua_{locale}.qm')
        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&xml_ua')
        self.toolbar = None 
        self.pluginIsActive = False
        self.dockwidget = None
        self.dockwidget_visible = False
        self.new_xml = ""

        self.map_canvas_context_handler = None
        # Сигнал layersAdded передає список усіх шарів, які були додані 
        # до проекту з моменту останнього виклику сигналу, а не тільки 
        # останній доданий шар. Тому, щоб визначити, який шар був доданий 
        # останнім, потрібно порівнювати поточний список шарів з 
        # попереднім станом. Це вимагає додаткової логіки для відстеження 
        # шарів, які вже існують.

        # Щоб уникнути повторного підключення сигналів до вже існуючих шарів,
        self.existing_layer_ids = set()
        # Підключаємо обробник до сигналу про додавання шару
        # Якщо у QGIS відбулася подія додавання шару, то генерується
        # сигнал layersAdded, який передає список УСІХ шарів



    def tr(self, message): # after load QGIS, without project
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        # #log_msg(logFile, "xml_ua")
        return QCoreApplication.translate('xml_ua', message)
    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        #log_msg(logFile)

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action
    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        self.dockwidget = None

        self.pluginIsActive = False

    def unload(self):
        """Відключає сигнали, видаляє елементи інтерфейсу та очищує ресурси при вивантаженні плагіна."""
        #log_msg(logFile, "Початок вивантаження плагіна.")

        # Від'єднуємо обробник контекстного меню полотна карти
        self.disconnect_map_canvas_context()

        # --- Початок змін: Надійне закриття всіх ресурсів ---
        # 1. Знаходимо всі існуючі док-віджети цього плагіна.
        existing_dockwidgets = self.iface.mainWindow().findChildren(xml_uaDockWidget)
        #log_msg(logFile, f"Знайдено {len(existing_dockwidgets)} док-віджетів для повного очищення.")

        # 2. Спочатку закриваємо всі вкладки та пов'язані з ними групи шарів у кожному віджеті.
        for dw in existing_dockwidgets:
            if hasattr(dw, 'opened_xmls') and dw.opened_xmls:
                opened_xmls_copy = list(dw.opened_xmls)
                for xml_data in opened_xmls_copy:
                    dw.process_action_close_xml(xml_data, force_close=True)

        # 3. Після закриття вкладок, видаляємо самі док-віджети з інтерфейсу QGIS.
        for dw in existing_dockwidgets:
            try:
                dw.closingPlugin.disconnect(self.onClosePlugin)
            except (TypeError, RuntimeError):
                pass
            self.iface.removeDockWidget(dw)
        self.dockwidget = None  # Очищуємо основне посилання
        # --- Кінець змін ---

        # Видаляємо дії та тулбар з інтерфейсу QGIS
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&xml_ua'),
                action)
            self.iface.removeToolBarIcon(action)
        # Видаляємо тулбар, якщо він існує
        if self.toolbar:
            try:
                self.iface.mainWindow().removeToolBar(self.toolbar)
                #log_msg(logFile, f"Тулбар '{self.toolbar.objectName()}' видалено.")
            except Exception as e:
                #log_msg(logFile, f"Не вдалося видалити тулбар: {e}")
                pass
            self.toolbar = None

        # Відключаємо глобальні сигнали проекту
        try:
            QgsProject.instance().layersAdded.disconnect(self.on_layers_added)
            #log_msg(logFile, "Сигнал 'layersAdded' успішно відключено.")
        except TypeError:
            # Сигнал не був підключений
            pass

    def disconnect_map_canvas_context(self):
        """Від'єднує обробник контекстного меню від полотна карти."""
        if hasattr(self, 'map_canvas_context_handler') and self.map_canvas_context_handler:
            canvas = self.iface.mapCanvas()
            if canvas:
                try:
                    canvas.contextMenuAboutToShow.disconnect(self.map_canvas_context_handler)
                    #log_msg(logFile, "Обробник контекстного меню полотна карти успішно від'єднано.")
                except TypeError:
                    # Ігноруємо помилку, якщо сигнал не був підключений
                    pass
            self.map_canvas_context_handler = None

    def on_feature_added(self, layer, feature_id):
        # QMessageBox.information(
        #     self.iface.mainWindow(),
        #     "Сигнал: on_feature_added",
        #     f"Додано фічу до шару: '{layer.name()}'"
        # )
        #log_msg(logFile, f"Додано фічу ID:{feature_id} до шару: '{layer.name()}'")
        pass


    def on_feature_removed(self, layer, feature_id):
        try:

            # QMessageBox.information(
            #     self.iface.mainWindow(),
            #     "Сигнал: on_feature_removed",
            #     f"Видалено фічу ID:{feature_id} з шару: '{layer.name()}'"
            # )
            #log_msg(logFile, f"Видалено фічу ID:{feature_id} з шару: '{layer.name()}'")
            pass
        except RuntimeError:
            #log_msg(logFile, "Перехоплено RuntimeError: шар вже видалено на рівні C++.")
            pass
            return

    def on_committed_features_removed(self, layer_id, feature_ids):
        """Передає керування док-віджету після видалення об'єктів."""
        # --- Початок змін: Виправлення помилки AttributeError ---
        # Сигнал committedFeaturesRemoved передає layer_id (рядок), а не об'єкт шару.
        # Отримуємо об'єкт шару за його ID.
        layer = QgsProject.instance().mapLayer(layer_id)
        if not layer:
            return # Шар міг бути видалений

        if self.dockwidget:
            self.dockwidget.handle_committed_features_removed(layer, feature_ids)
        # --- Кінець змін ---

    def on_geometry_changed(self, layer, feature_id, geom):
        # QMessageBox.information(
        #     self.iface.mainWindow(),
        #     "Сигнал: on_geometry_changed",
        #     f"Змінено геометрію для шару: '{layer.name()}'\nID фічі: {feature_id}"
        # )
        #log_msg(logFile, f"Геометрію змінено для шару '{layer.name()}', feature_id: {feature_id}")
        if self.dockwidget and self.is_layer_in_opened_xmls_group(layer):
            self.dockwidget.update_xml_from_geometry_change(layer, feature_id)

    def is_layer_in_opened_xmls_group(self, layer):
        """
        Перевіряє, чи належить шар до однієї з груп, що входять до opened_xmls.

        Args:
            layer (QgsVectorLayer): Шар для перевірки.

        Returns:
            bool: True, якщо шар належить до однієї з груп, інакше False.
        """

        layer_name = layer.name()
        #log_msg(logFile, f"'{layer_name}'")

        if not self.dockwidget or not hasattr(self.dockwidget, 'opened_xmls'):
            return False

        project = QgsProject.instance()
        root = project.layerTreeRoot()

        for xml_data in self.dockwidget.opened_xmls:
            group_name = xml_data.group_name
            group = root.findGroup(group_name)

            if group:
                for child in group.children():
                    if isinstance(child, QgsLayerTreeLayer):
                        if child.layer() == layer:
                            return True
        return False
    

    def run(self):
        """
        Executes the plugin's main functionality.
        Called from on_open_tool()

        This method performs the following actions:
        1. Logs the function call.
        2. Checks if a QGIS project is open. If no project is open, logs a message and shows a warning to the user.
        3. If the plugin is not active, activates the plugin and initializes the dock widget if it is not already created.
        4. Adds the dock widget to the QGIS interface and displays it.

        Returns:
            None
        """

        if not QgsProject.instance().fileName():
            #log_msg(logFile, "Немає відкритого проекту. Плагін не буде запущено.")
            self.iface.messageBar().pushMessage(
                "XML-UA",
                "Спочатку треба відкрити проект.",
                level=Qgis.Warning
            )
            return
        
        # --- Початок змін: Створення віджета без показу ---
        # Гарантуємо, що док-віджет існує, але не робимо його видимим.
        # Видимість контролюється виключно методом show_dockwidget (toggle).
        if self.dockwidget is None:
            # #log_msg(logFile, "Док-віджет не існує. Створюємо його у фоновому режимі.")
            self.dockwidget = xml_uaDockWidget(parent=self.iface.mainWindow(), iface=self.iface, plugin=self)
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)
            self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.dockwidget)
            self.dockwidget.hide() # Явно приховуємо після створення
        # --- Кінець змін ---
    def on_save_tool(self):
        #log_msg(logFile)
        if self.dockwidget is None:
            #log_msg(logFile, "Error: dockwidget is None")
            QMessageBox.warning(self.iface.mainWindow(), "Помилка", "Док віджет не ініціалізовано.")
            return
        self.dockwidget.process_action_save()
        return
    def on_save_as_template_tool(self):
        #log_msg(logFile)
        if self.dockwidget is None:
            #log_msg(logFile, "Error: dockwidget is None")
            QMessageBox.warning(self.iface.mainWindow(), "Помилка", "Док віджет не ініціалізовано.")
            return
        self.dockwidget.process_action_save_as_template()
        return
    
    
    def on_check_tool(self):
        #log_msg(logFile)
        self.dockwidget.process_action_check()
        return
    
    
    def on_open_tool(self): 
        # Обробка дії "Відкрити XML"
        # Перевіряємо, чи проект відкритий
        
        if not QgsProject.instance().fileName():
            self.iface.messageBar().pushMessage(
                "XML-UA",
                "Спочатку треба відкрити проект.",
                level=Qgis.Warning
            )
            return

        # 
        self.run()

        # --- Початок змін: Відкриття файлу без показу віджета ---
        # Переконуємося, що віджет існує, і викликаємо логіку відкриття файлу.
        if self.dockwidget:
            self.dockwidget.process_action_open()
        else:
            #log_msg(logFile, "Критична помилка: dockwidget не був створений перед викликом on_open_tool.")
            pass
        # Підключаємо сигнали для всіх шарів
        # self.connect_layer_signals()
    
    def on_clear_tool(self):
        """Обробляє дію "Закрити", закриваючи поточний активний XML-файл."""
        if self.dockwidget and self.dockwidget.current_xml:
            #log_msg(logFile, f"Закриття поточного файлу: {self.dockwidget.current_xml.path}")
            self.dockwidget.process_action_close_xml(self.dockwidget.current_xml)
        else:
            #log_msg(logFile, "Немає активного файлу для закриття.")
            QMessageBox.information(self.iface.mainWindow(), "Інформація", "Немає активного файлу для закриття.")


    def clear_widget_data(self): 

        """Clears data from the dock widget."""
        if self.dockwidget is None:
            return  # Nothing to clear if the dockwidget doesn't exist

        # log_msg(logFile)

        # root = QgsProject.instance().layerTreeRoot()
        # if self.xml_layers:  # Check if xml_layers is not None
        #     group = root.findGroup(self.xml_layers.group_name)
        #     if group:
        #         root.removeChildNode(group)

        # Close all tabs except specified ones
        tabs_to_keep = ["Структура", "Реквізити", "Ділянка"]
        for i in range(self.dockwidget.tabWidget.count() -1, -1, -1): # Зворотній порядок!
            tab_name = self.dockwidget.tabWidget.tabText(i)
            if tab_name not in tabs_to_keep:
                # self.dockwidget.tabWidget.removeTab(i)
                if self.dockwidget.tabWidget.count() > 0:
                    #QMessageBox.warning(self.iface.mainWindow(), "clear_widget_data", f"видаляємо таб №{i} {tab_name}")
                    self.dockwidget.tabWidget.removeTab(i)

        self.dockwidget.closed_tabs = []

        # Clear data in TreeView and TableViews (if they exist)
        try:
            tree_model = self.dockwidget.treeViewXML.model
            meta_model = self.dockwidget.tableViewMetadata.model()
            parcel_model = self.dockwidget.tableViewParcel.model()
            #set headers after clearing
            for model in [tree_model, meta_model, parcel_model]:
                if model.rowCount() > 0:
                    model.removeRows(0, model.rowCount())
                model.setHorizontalHeaderLabels(["Елемент", "Значення"])

        except AttributeError:
            #log_msg(logFile, f"AttributeError: {AttributeError}")
            pass # Handle the case where the dockwidget might not be fully initialized or if some views are missing.

        self.dockwidget.setWindowTitle("XML-файл обміну кадастровою інформацією")
        self.dockwidget.xml_file_name = ""
    def remove_temporary_layers(self):
        """
            Clears all temporary layers ("memory") and 
            empty groups (non-recursively) from the QGIS project.

            Reference: on_clear_tool
        """
        # потрібно очистити проект від тимчасових шарів

        # log_calls(logFile, "Очистка даних проекту...")
        project = QgsProject.instance()
        root = project.layerTreeRoot()
        # 1. Remove temporary layers
        layers_to_remove = []
        for layer_id, layer in project.mapLayers().items():
            if layer.dataProvider().name() == 'memory':
                layers_to_remove.append(layer_id)
        for layer_id in layers_to_remove:
            project.removeMapLayer(layer_id)


        def remove_empty_groups(group):
            """Рекурсивно видаляє порожні групи з дерева шарів."""
            groups_to_remove = []
            for child in group.children():
                if isinstance(child, QgsLayerTreeGroup):
                    remove_empty_groups(child)  # Рекурсивний виклик для дочірніх груп
                    if len(child.children()) == 0:
                        groups_to_remove.append(child)
            for group_to_remove in groups_to_remove:
                # #log_msg(logFile, f"Видалено порожню групу: {group_to_remove.name()}")
                group.removeChildNode(group_to_remove)
        # Видалення порожніх груп
        remove_empty_groups(root)


    def show_dockwidget(self):
        """
        Керує створенням та видимістю док-віджета.

        Цей метод працює як перемикач (toggle).
        - Якщо док-віджет не існує, він створюється і показується.
        - Якщо док-віджет існує, але прихований, він показується.
        - Якщо док-віджет існує і видимий, він приховується.

        Викликається:
        - `tools_button.clicked`: при натисканні на головну іконку плагіна на панелі інструментів.
        """
        # Спочатку перевіряємо, чи є у нас посилання на віджет
        # --- Початок змін: Надійний пошук віджета ---
        # Завжди шукаємо віджет в інтерфейсі, оскільки посилання self.dockwidget
        # може бути застарілим після перезавантаження плагіна.
        found_dockwidget = self.iface.mainWindow().findChild(xml_uaDockWidget, "")
        if self.dockwidget is None:
            # Якщо віджет не знайдено, створюємо новий екземпляр
            ##log_msg(logFile, "Док-віджет не знайдено. Створюємо новий.")
            self.dockwidget = xml_uaDockWidget(parent=self.iface.mainWindow(), iface=self.iface, plugin=self)
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)
            self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.dockwidget)
            self.dockwidget.hide() # Завжди приховуємо після створення
        # --- Кінець змін ---

        # --- Початок змін: Логіка видимості віджета ---
        # Показуємо віджет, тільки якщо є відкриті файли.
        if self.dockwidget.opened_xmls:
            if self.dockwidget.isVisible():
                self.dockwidget.hide()
            else:
                self.dockwidget.show()
                self.dockwidget.raise_()
        else:
            # Якщо файлів немає, віджет залишається прихованим, і ми показуємо повідомлення.
            self.dockwidget.hide()
            self.iface.messageBar().pushMessage("Інфо", "Відкрийте XML-файл, щоб побачити його структуру.", level=Qgis.Info, duration=4)
        # --- Кінець змін ---
    def initGui(self):
        """Створює меню та панель інструментів після запуску QGIS."""
        self.create_toolbar_and_menu()
        
        # Підключаємо сигнали тут, оскільки initGui викликається один раз при старті QGIS
        try:
            QgsProject.instance().layersAdded.disconnect(self.on_layers_added)
        except TypeError:
            pass # Ігноруємо, якщо не було підключено
        QgsProject.instance().layersAdded.connect(self.on_layers_added)

        # Налаштовуємо контекстне меню полотна карти
        from .map_canvas_context import setup_map_canvas_context
        self.disconnect_map_canvas_context() # Спочатку від'єднуємо старе, якщо є
        self.map_canvas_context_handler = setup_map_canvas_context(self.iface, self)

    def reload_map_canvas_context(self):
        """Перезавантажує обробник контекстного меню полотна карти."""
        #log_msg(logFile, "Перезавантаження контекстного меню полотна карти.")
        from .map_canvas_context import setup_map_canvas_context
        self.disconnect_map_canvas_context()
        self.map_canvas_context_handler = setup_map_canvas_context(self.iface, self)

    def connect_picket_layer_signals(self):
        """
        Підключає сигнал editingStopped до всіх існуючих шарів 'Вузли' в проекті.
        Викликається після того, як dockwidget гарантовано створено.
        """
        if not self.dockwidget:
            return

        project = QgsProject.instance()
        for layer_id, layer in project.mapLayers().items():
            if layer.name() == "Вузли":
                # Перевіряємо, чи сигнал ще не підключено, щоб уникнути дублювання
                layer.editingStopped.connect(lambda l=layer: self.dockwidget.on_picket_layer_editing_stopped(l))
                #log_msg(logFile, f"Відкладено підключено editingStopped для існуючого шару '{layer.name()}'")
        """Створює меню та панель інструментів після запуску QGIS."""
        self.create_toolbar_and_menu()

    def create_menu(self):
        """Створює меню плагіна."""
        # Цей метод залишається для можливого майбутнього розширення
        pass


    def create_toolbar_and_menu(self):

        # Шукаємо тулбар з ім'ям "xml_ua" та класом "QToolBar"
        existing_toolbar = self.iface.mainWindow().findChild(QToolBar, "xml_ua")

        if existing_toolbar:
            ##log_msg(logFile, f"Тулбар '{existing_toolbar.objectName()}' вже існує. Використовуємо його.")
            self.toolbar = existing_toolbar  # Використовуємо знайдений тулбар
        else:
            ##log_msg(logFile, f"Тулбар 'xml_ua' не знайдено. Створюємо новий.")
            self.toolbar = self.iface.addToolBar(u'xml_ua') # Переносимо сюди
            self.toolbar.setObjectName(u'xml_ua') # І сюди

        # Тепер ми впевнені, що self.toolbar існує (новий або вже існуючий)
        # Далі створюємо меню і кнопки, та додаємо їх на тулбар

        icon_path = ':/plugins/xml_ua/icon.png'
        self.tools_menu = QMenu(self.iface.mainWindow())

        self.action_new_tool = QAction("Новий XML", self.iface.mainWindow())
        # Отримуємо стандартну іконку "Новий" з QGIS
        new_icon = self.iface.mainWindow().style().standardIcon(QStyle.SP_FileIcon)
        self.action_new_tool.setIcon(new_icon)


        self.action_open_tool = QAction("Відкрити", self.iface.mainWindow())

        # Отримуємо стандартну іконку "Відкрити" з QGIS
        open_icon = self.iface.mainWindow().style().standardIcon(QStyle.SP_DirOpenIcon)
        self.action_open_tool.setIcon(open_icon)

        self.action_save_tool = QAction("Зберегти", self.iface.mainWindow())
        # Отримуємо стандартну іконку "Зберегти" з QGIS
        save_icon = self.iface.mainWindow().style().standardIcon(QStyle.SP_DialogSaveButton)
        self.action_save_tool.setIcon(save_icon)

        self.action_save_as_template_tool = QAction("Зберегти як шаблон...", self.iface.mainWindow())
        # Отримуємо стандартну іконку "Зберегти як..." з QGIS
        save_as_icon = QIcon(QgsApplication.iconPath("mActionFileSaveAs.svg"))
        self.action_save_as_template_tool.setIcon(save_as_icon)

        # Встановлюємо початковий стан неактивності
        self.action_save_tool.setEnabled(False)
        self.action_save_as_template_tool.setEnabled(False)

        self.action_check_tool = QAction("Перевірити", self.iface.mainWindow())
        # Отримуємо стандартну іконку "Застосувати" (галочка) з QGIS
        check_icon = self.iface.mainWindow().style().standardIcon(QStyle.SP_DialogApplyButton)
        self.action_check_tool.setIcon(check_icon)
        self.action_clear_data = QAction("Закрити", self.iface.mainWindow())
        # Іконка "видалити шар" (червоний мінус), як просив користувач
        close_icon = self.iface.mainWindow().style().standardIcon(QStyle.SP_DialogCloseButton)
        self.action_clear_data.setIcon(close_icon)

        # 📌 Відновлення з копії
        self.action_restore_backup = QAction("Відновити з резервної копії...", self.iface.mainWindow())
        restore_icon = self.iface.mainWindow().style().standardIcon(QStyle.SP_BrowserReload)
        self.action_restore_backup.setToolTip("Відновити активний файл з його резервної копії, створеної при відкритті")
        self.action_restore_backup.setIcon(restore_icon)

        self.action_check_tool.setEnabled(False)
        self.action_clear_data.setEnabled(False)
        self.action_restore_backup.setEnabled(False)

        self.tools_menu.addActions([self.action_new_tool, self.action_open_tool, self.action_save_tool, self.action_save_as_template_tool, self.action_check_tool])
        self.tools_menu.addAction(self.action_clear_data)
        self.tools_menu.addAction(self.action_restore_backup)
        #self.tools_menu.addAction(self.action_restore_tabs)

        self.tools_button = QToolButton()
        self.tools_button.setIcon(QIcon(icon_path))
        self.tools_button.setMenu(self.tools_menu)
        self.tools_button.setPopupMode(QToolButton.MenuButtonPopup)

        #self.action_restore_tabs.setEnabled(False)
        self.dockwidget = None

        connector.connect(self.action_new_tool, "triggered", self.on_new_tool)
        connector.connect(self.action_open_tool, "triggered", self.on_open_tool)
        connector.connect(self.action_save_tool, "triggered", self.on_save_tool)
        connector.connect(self.action_save_as_template_tool, "triggered", self.on_save_as_template_tool)
        connector.connect(self.action_check_tool, "triggered", self.on_check_tool)
        connector.connect(self.action_clear_data, "triggered", self.on_clear_tool)
        connector.connect(self.action_restore_backup, "triggered", self.restore_from_copy)
        
        self.tools_button.setObjectName("xml_ua_tools_button")
        self.toolbar.addWidget(self.tools_button)

        connector.connect(self.tools_button, "clicked", self.show_dockwidget)

    def on_layers_added(self, layers):
        """
        Обробник сигналу про додавання шарів до проекту.  Підключає сигнали лише до нових шарів.
        """
        for layer in layers:
            if isinstance(layer, QgsVectorLayer):
                # Використовуємо lambda для захоплення поточного шару `layer`
                layer.featureAdded.connect(lambda fid, l=layer: self.on_feature_added(l, fid))
                layer.featureDeleted.connect(lambda fid, l=layer: self.on_feature_removed(l, fid))
                layer.committedFeaturesRemoved.connect(lambda l, fids: self.on_committed_features_removed(l, fids))
                layer.geometryChanged.connect(lambda fid, geom, l=layer: self.on_geometry_changed(l, fid, geom))

                # Підключаємо editingStopped для шару "Вузли"
                if layer.name() == "Вузли" and self.dockwidget:
                    try:
                        # Використовуємо lambda для захоплення поточного шару `l`
                        layer.editingStopped.connect(lambda l=layer: self.dockwidget.on_picket_layer_editing_stopped(l))
                    except Exception as e:
                        log_msg(logFile, f"Помилка при підключенні editingStopped для шару '{layer.name()}': {e}")


    def restore_from_copy(self):
        """Відновлює активний XML-файл з його резервної копії."""
        #log_msg(logFile, "Запущено процедуру відновлення з копії.")

        if not self.dockwidget or not self.dockwidget.current_xml:
            QMessageBox.warning(self.iface.mainWindow(), "Помилка", "Немає активного файлу для відновлення.")
            return
        
        active_xml = self.dockwidget.current_xml
        original_path = active_xml.path
        backup_path = active_xml.backup_path

        if not backup_path or not os.path.exists(backup_path):
            QMessageBox.warning(self.iface.mainWindow(), "Помилка", f"Резервну копію не знайдено за шляхом:\n{backup_path}")
            return

        if not backup_path or not os.path.exists(backup_path):
            QMessageBox.warning(self.iface.mainWindow(), "Помилка", f"Резервну копію не знайдено за шляхом:\n{backup_path}")
            return

        reply = QMessageBox.question(self.iface.mainWindow(), "Підтвердження відновлення",
                                     f"Ви впевнені, що хочете відновити файл\n'{os.path.basename(original_path)}'\nз його резервної копії? Усі незбережені зміни буде втрачено.",
                                     QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
        
        if reply == QMessageBox.No:
            #log_msg(logFile, "Відновлення скасовано користувачем.")
            return

        try:
            # 1. Закриваємо вкладку та групу примусово
            self.dockwidget.process_action_close_xml(active_xml, force_close=True)
            # 2. Замінюємо оригінальний файл копією
            shutil.copy2(backup_path, original_path)
            #log_msg(logFile, f"Файл '{original_path}' відновлено з '{backup_path}'.")
            # 3. Відкриваємо відновлений файл
            self.dockwidget.open_xml_file(original_path)
            self.iface.messageBar().pushMessage("Диск:", f"Файл '{os.path.basename(original_path)}' успішно відновлено.", level=Qgis.Success, duration=5)
        except Exception as e:
            #log_msg(logFile, f"Помилка під час відновлення: {e}")
            QMessageBox.critical(self.iface.mainWindow(), "Помилка відновлення", f"Сталася помилка: {e}")

    def on_new_tool(self):

        """Обробник для створення нового XML-файлу."""
        #log_msg(logFile)
        # Створюємо екземпляр класу для створення нового файлу
        creator = NewXmlCreator(self.iface, self)
        # Запускаємо процес
        creator.execute()
